### Negative case: Transfer  money from one account without enough balance to another account with different owner
POST http://localhost:4111/api/v1/accounts/transfer
accept: */*
Content-Type: application/json
Authorization: Basic e3tleGlzdGluZ191c2VybmFtZX19Ont7ZXhpc3RpbmdfcGFzc3dvcmR9fQ==

{
  "senderAccountId": {{account_id}},
  "receiverAccountId": 3,
  "amount": 10000
}

