### Negative case: Deposit money to another person's account
POST http://localhost:4111/api/v1/accounts/deposit
accept: */*
Content-Type: application/json
Authorization: Basic e3tleGlzdGluZ191c2VybmFtZX19Ont7ZXhpc3RpbmdfcGFzc3dvcmR9fQ==

{
  "id": 3,
  "balance": 100
}

