### Negative case: Create user with blank user_name
POST http://localhost:4111/api/v1/admin/users
Authorization: 
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "username": "",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

