### Negative case: Create user with  password without one lower case character
POST http://localhost:4111/api/v1/admin/users
Authorization: 
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "username": "test{{$timestamp}}",
  "password": "Tdtttttt$",
  "role": "USER"
}

