### Negative case: Create user with  role not from list "ADMIN", "USER"
POST http://localhost:4111/api/v1/admin/users
Authorization: 
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "username": "test{{$timestamp}}",
  "password": "Tdtt4tttt$",
  "role": "EDITOR"
}

