### Negative case: Create user with 16 char in user_name
POST http://localhost:4111/api/v1/admin/users
Authorization: 
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "username": "fgfhncnthfkdncbd",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

